# Generated by Django 3.0.8 on 2020-08-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20200810_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='cardnumber',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
