# Generated by Django 3.0.8 on 2020-08-10 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_cardpost_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='imagelink',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
