# Generated by Django 3.0.8 on 2020-08-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_cardpost_imagelink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpost',
            name='image',
            field=models.ImageField(blank=True, default='/home/jesse/p/dg2/static/img/cards/03-04-Bowman-LeBron.jpg', null=True, upload_to='images'),
        ),
    ]
