# Generated by Django 3.0.8 on 2020-08-11 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0009_auto_20200810_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='ebayafflink',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
