# Generated by Django 3.0.8 on 2020-08-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0010_cardpost_ebayafflink'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='changepercent',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='high',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='low',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='salesvolume',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='transactionvolume',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
