# Generated by Django 3.0.8 on 2020-08-12 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0013_cardpost_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardpost',
            name='transactionvolume',
            field=models.CharField(blank=True, default='N/A', max_length=127, null=True),
        ),
    ]
