# Generated by Django 3.0.8 on 2020-08-12 21:21

from django.db import migrations, models
import gsheets.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0014_auto_20200812_0457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardcount', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('changepercent', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('salesvolume', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('average', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('transactionvolume', models.CharField(blank=True, default='N/A', max_length=127, null=True)),
                ('low', models.CharField(blank=True, default=None, max_length=127, null=True)),
                ('high', models.CharField(blank=True, default=None, max_length=127, null=True)),
            ],
            bases=(gsheets.mixins.SheetPullableMixin, models.Model),
        ),
    ]
