# Generated by Django 3.0.8 on 2020-08-12 21:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0015_stats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stats',
            name='id',
        ),
        migrations.AddField(
            model_name='stats',
            name='guid',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
    ]
