# Generated by Django 3.0.8 on 2020-08-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0016_auto_20200812_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='slug',
            field=models.SlugField(blank=True, default=None, max_length=200, null=True, unique=True),
        ),
    ]
