# Generated by Django 3.0.8 on 2020-08-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0019_auto_20200820_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='p8a',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='p8c',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='p8p',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='p8t',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='p8v',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='ra',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='rc',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='rp',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='rt',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='rv',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
