# Generated by Django 3.0.8 on 2020-08-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0021_auto_20200821_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardpost',
            name='p8a',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p8c',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p8h',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p8p',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p8t',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p8v',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9a',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9c',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9h',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9p',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9t',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='p9v',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='ra',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='rc',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='rh',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='rp',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='rt',
        ),
        migrations.RemoveField(
            model_name='cardpost',
            name='rv',
        ),
        migrations.AlterField(
            model_name='cardpost',
            name='transactionvolume',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
