# Generated by Django 3.0.8 on 2020-08-21 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0022_auto_20200821_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='variations',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
