# Generated by Django 3.0.8 on 2020-08-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0023_cardpost_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardpost',
            old_name='tagg',
            new_name='tag1',
        ),
        migrations.AddField(
            model_name='cardpost',
            name='tag2',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='tag3',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
