# Generated by Django 3.0.8 on 2020-08-30 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0024_auto_20200822_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='bgs10',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='bgs8',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='bgs85',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='bgs9',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='cardpost',
            name='bgs95',
            field=models.CharField(blank=True, default=None, max_length=127, null=True),
        ),
    ]
