# Generated by Django 3.0.8 on 2020-08-19 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='text',
        ),
    ]
